Repository software-students-fall2021/project-setup-gotnotes, pull requests merged in 2021-11, with the labels that each got.

#83 Had287 list item grid item
  front-end/gotnotes/public/uniLogos/cuny.png
  front-end/gotnotes/src/assets/mocks/mockData.js
  front-end/gotnotes/src/components/Mobile/GridItem/index.js
  front-end/gotnotes/src/components/Mobile/GridItem/styles.scss
  front-end/gotnotes/src/components/Mobile/ListItem/index.js
  front-end/gotnotes/src/components/Mobile/ListItem/styles.scss
  front-end/gotnotes/src/layouts/Mobile/MobileLayoutSelector.js
  front-end/gotnotes/src/pages/Search/Courses/index.js
  front-end/gotnotes/src/pages/Search/Courses/styles.scss
  front-end/gotnotes/src/pages/Search/Files/index.js
  front-end/gotnotes/src/pages/Search/Files/styles.scss
  front-end/gotnotes/src/pages/Search/Unis/index.js
  front-end/gotnotes/src/pages/Search/Unis/styles.scss
Labels: spike

#85 Had287 add file page
  front-end/gotnotes/src/components/Mobile/PageTitle/index.js
  front-end/gotnotes/src/components/Mobile/PageTitle/styles.scss
  front-end/gotnotes/src/components/Mobile/PageTıtle/index.js
  front-end/gotnotes/src/pages/AddFile/index.js
  front-end/gotnotes/src/pages/AddFile/styles.scss
Labels: spike

#86 Kaan university components
  front-end/gotnotes/src/components/Mobile/PictureGrid/index.js
  front-end/gotnotes/src/components/Mobile/PictureGrid/styles.scss
  front-end/gotnotes/src/pages/Account/Account/index.js
  front-end/gotnotes/src/pages/Account/Account/styles.scss
Labels: spike

#105 Had287 grid layout overhaul
  front-end/package-lock.json
  front-end/package.json
  front-end/public/lorem.docx
  front-end/public/lorem.pdf
  front-end/src/assets/mocks/mockData.js
  front-end/src/components/AdminToolbar/index.js
  front-end/src/components/Mobile/BottomNav/styles.scss
  front-end/src/components/Mobile/Breadcrumbs/index.js
  front-end/src/components/Mobile/Breadcrumbs/styles.scss
  front-end/src/components/Mobile/Button/index.js
  front-end/src/components/Mobile/ChatBubble/index.js
  front-end/src/components/Mobile/ChatBubble/styles.scss
  front-end/src/components/Mobile/CommentIcon/index.js
  front-end/src/components/Mobile/CommentIcon/styles.scss
  front-end/src/components/Mobile/CommentViewer/index.js
  front-end/src/components/Mobile/CommentViewer/styles.scss
  front-end/src/components/Mobile/DislikeIcon/index.js
  front-end/src/components/Mobile/DislikeIcon/styles.scss
  front-end/src/components/Mobile/GridItem/index.js
  front-end/src/components/Mobile/GridItem/styles.scss
  front-end/src/components/Mobile/LikeIcon/index.js
  front-end/src/components/Mobile/LikeIcon/styles.scss
  front-end/src/components/Mobile/ListItem/index.js
  front-end/src/components/Mobile/ListItem/styles.scss
  front-end/src/components/Mobile/MessageInput/index.js
  front-end/src/components/Mobile/MessageInput/styles.scss
  front-end/src/components/Mobile/NotificationBell/index.js
  front-end/src/components/Mobile/PageTitle/index.js
  front-end/src/components/Mobile/PageTitle/styles.scss
  front-end/src/components/Mobile/SearchHigherOrder/GridListToggle/styles.scss
  front-end/src/components/Mobile/SearchHigherOrder/styles.scss
  front-end/src/default.scss
  front-end/src/layouts/Mobile/MobileLayoutSelector.js
  front-end/src/pages/Search/Courses/styles.scss
  front-end/src/pages/Search/FileDetails/index.js
  front-end/src/pages/Search/FilePreview/index.js
  front-end/src/pages/Search/Files/styles.scss
  front-end/src/pages/Search/Unis/styles.scss
  front-end/yarn.lock
Labels: task, frontend

#110 Had287 back end
  back-end/.env
  back-end/.gitignore
  back-end/index.js
  back-end/package.json
  back-end/yarn.lock
Labels: task, backend

#112 Had287 file details
  front-end/package.json
  front-end/src/App.js
  front-end/src/assets/mocks/mockData.js
  front-end/src/components/Mobile/FileData/index.js
  front-end/src/components/Mobile/FileData/styles.scss
  front-end/src/components/Mobile/GridItem/index.js
  front-end/src/components/Mobile/Icons/CommentIcon/index.js
  front-end/src/components/Mobile/Icons/CommentIcon/styles.scss
  front-end/src/components/Mobile/Icons/DislikeIcon/index.js
  front-end/src/components/Mobile/Icons/DislikeIcon/styles.scss
  front-end/src/components/Mobile/Icons/DownloadIcon/index.js
  front-end/src/components/Mobile/Icons/DownloadIcon/styles.scss
  front-end/src/components/Mobile/Icons/LikeIcon/index.js
  front-end/src/components/Mobile/Icons/LikeIcon/styles.scss
  front-end/src/components/Mobile/Icons/NotificationBell/index.js
  front-end/src/components/Mobile/Icons/NotificationBell/styles.scss
  front-end/src/components/Mobile/ListItem/index.js
  front-end/src/components/Mobile/Navigations/BottomNav/index.js
  front-end/src/components/Mobile/Navigations/BottomNav/styles.scss
  front-end/src/components/Mobile/Navigations/Breadcrumbs/index.js
  front-end/src/components/Mobile/Navigations/Breadcrumbs/styles.scss
  front-end/src/components/Mobile/Navigations/PageTitle/index.js
  front-end/src/components/Mobile/Navigations/PageTitle/styles.scss
  front-end/src/components/Mobile/PictureGrid/index.js
  front-end/src/components/Mobile/UserAvatar/index.js
  front-end/src/components/Mobile/UserAvatar/styles.scss
  front-end/src/components/Mobile/UserDataViewer/index.js
  front-end/src/components/Mobile/UserDataViewer/styles.scss
  front-end/src/default.scss
  front-end/src/layouts/Mobile/MobileLayoutSelector.js
  front-end/src/pages/AddFile/index.js
  front-end/src/pages/Search/FileDetails/index.js
  front-end/src/pages/Search/FileDetails/styles.scss
Labels: task, frontend

#116 Had287 comment viewer
  front-end/src/components/Mobile/Comment/index.js
  front-end/src/components/Mobile/Comment/styles.scss
  front-end/src/components/Mobile/CommentViewer/index.js
  front-end/src/components/Mobile/CommentViewer/styles.scss
  front-end/src/components/Mobile/FileData/index.js
  front-end/src/components/Mobile/Icons/LikeIcon/index.js
  front-end/src/components/Mobile/Icons/ReplyIcon/index.js
  front-end/src/components/Mobile/Icons/ReplyIcon/styles.scss
  front-end/src/components/Mobile/UserAvatar/index.js
  front-end/src/components/Mobile/UserAvatar/styles.scss
  front-end/src/components/Mobile/UserDataViewer/index.js
  front-end/src/pages/Search/FileDetails/index.js
Labels: task, frontend

#120 Had287 backend & tests
  back-end/.env
  back-end/Controllers/ChatController/index.js
  back-end/Controllers/ChatController/index.test.js
  back-end/Controllers/CourseController/index.js
  back-end/Controllers/CourseController/index.test.js
  back-end/Controllers/FileController/index.js
  back-end/Controllers/FileController/index.test.js
  back-end/Controllers/FilesController/index.js
  back-end/Controllers/FilesController/index.test.js
  back-end/Controllers/UniController/index.js
  back-end/Controllers/UniController/index.test.js
  back-end/Controllers/UserController/index.js
  back-end/Controllers/UserController/index.test.js
  back-end/Controllers/index.int.test.js
  back-end/Controllers/index.js
  back-end/Models/Chat/index.js
  back-end/Models/Comment/index.js
  back-end/Models/Course/index.js
  back-end/Models/File/index.js
  back-end/Models/Uni/index.js
  back-end/Models/User/index.js
  back-end/Models/index.js
  back-end/index.int.test.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/Account/index.js
  back-end/routes/Account/index.test.js
  back-end/routes/AddFile/index.js
  back-end/routes/AddFile/index.test.js
  back-end/routes/Chat/index.js
  back-end/routes/Chat/index.test.js
  back-end/routes/Search/Courses/index.js
  back-end/routes/Search/Courses/index.test.js
  back-end/routes/Search/File/index.js
  back-end/routes/Search/File/index.test.js
  back-end/routes/Search/Files/index.js
  back-end/routes/Search/Files/index.test.js
  back-end/routes/Search/Unis/index.js
  back-end/routes/Search/Unis/index.test.js
  back-end/routes/Search/index.int.test.js
  back-end/routes/Search/index.js
  back-end/routes/index.int.test.js
  back-end/routes/index.js
  back-end/server.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Mobile/Button/index.js
  front-end/src/components/Mobile/ListItem/index.js
  front-end/src/pages/Search/Courses/index.js
  front-end/src/pages/Search/Files/index.js
  front-end/src/services/SearchTabServices/CourseInteractionHandler/index.js
  front-end/src/services/SearchTabServices/FileInteractionHandler/index.js
  front-end/src/services/SearchTabServices/index.js
  front-end/yarn.lock
Labels: spike

#121 commented out breaking template routes
  back-end/routes/Account/index.js
  back-end/routes/AddFile/index.js
  back-end/routes/Chat/index.js
  back-end/routes/Search/Courses/index.js
  back-end/routes/Search/File/index.js
  back-end/routes/Search/Files/index.js
  back-end/routes/Search/Unis/index.js
Labels: spike, backend

#123 mock data from mockaroo included in the mock folder at back-end, mock…
  back-end/Mock/ChatsMockData/chats.json
  back-end/Mock/CommentsMockData/comments.json
  back-end/Mock/CoursesMockData/courses.json
  back-end/Mock/FilesMockData/file.json
  back-end/Mock/UnisMockData/unis.json
  back-end/Mock/UsersMockData/users.json
  back-end/Models/File/index.js
  back-end/Models/User/index.js
Labels: spike, backend

#125 back-end refactored to fit into MVC folder structure
  back-end/routes/Account/index.js
  back-end/routes/AddFile/index.js
  back-end/routes/AddFile/index.test.js
  back-end/routes/Chat/index.js
  back-end/routes/Search/Courses/index.js
  back-end/routes/Search/File/index.js
  back-end/routes/Search/Files/index.js
  back-end/routes/Search/Unis/index.js
  back-end/routes/Search/index.js
  back-end/routes/index.js
  back-end/server.js
Labels: task, backend

#141 Karakas uni service
  back-end/Services/CourseService/index.js
  back-end/Services/CourseService/index.test.js
  back-end/Services/UniService/index.js
  back-end/Services/UniService/index.test.js
Labels: task, backend

#143 Had287 file service tests
  back-end/Services/FileService/index.js
  back-end/Services/FileService/index.test.js
  front-end/package-lock.json
  front-end/package.json
  front-end/yarn.lock
Labels: task, backend

#144 Had287 user service tests
  back-end/Services/UserService/index.js
  back-end/Services/UserService/index.test.js
Labels: task, backend

#145 Had287 course services tests
  back-end/Services/CourseService/index.js
  back-end/Services/CourseService/index.test.js
Labels: task, backend

#146 Had287 course services
  back-end/Services/CourseService/index.js
  back-end/Services/CourseService/index.test.js
Labels: task, backend

#150 Chat service now supports getting and pushing data to and from atlas
  back-end/Models/User/index.js
  back-end/Services/ChatService/index.js
  back-end/Services/CommentService/index.js
  back-end/Services/CourseService/index.js
  back-end/Services/Database/index.js
  back-end/Services/FileService/index.js
  back-end/Services/UniService/index.js
  back-end/Services/UserService/index.js
Labels: backend

#156 Karakas database testing
  back-end/Services/ChatService/index.test.js
  back-end/Services/CommentService/index.test.js
  back-end/Services/UniService/index.test.js
Labels: spike
