Repository software-students-fall2021/project-setup-gotnotes, pull requests merged in 2021-12, with the labels that each got.

#164 Had287 back end mongo integration
  back-end/.env
  back-end/Controllers/CommentController/index.js
  back-end/Controllers/CourseController/index.js
  back-end/Controllers/FileController/index.js
  back-end/Controllers/FilesController/index.js
  back-end/Controllers/UniController/index.js
  back-end/Controllers/UserController/index.js
  back-end/Controllers/index.js
  back-end/Models/Comment/index.js
  back-end/Models/Course/index.js
  back-end/Models/File/index.js
  back-end/Models/Uni/index.js
  back-end/Models/User/index.js
  back-end/Services/Auth/index.js
  back-end/Services/Auth/index.test.js
  back-end/Services/ChatService/index.test.js
  back-end/Services/CommentService/index.js
  back-end/Services/CommentService/index.test.js
  back-end/Services/CourseService/index.js
  back-end/Services/CourseService/index.test.js
  back-end/Services/Database/index.js
  back-end/Services/FileService/index.js
  back-end/Services/FileService/index.test.js
  back-end/Services/UniService/index.js
  back-end/Services/UniService/index.test.js
  back-end/Services/UserService/index.js
  back-end/Services/UserService/index.test.js
  back-end/Services/Validation/index.js
  back-end/package-lock.json
  back-end/routes/Account/index.js
  back-end/routes/Auth/Admin/index.js
  back-end/routes/Auth/Login/index.js
  back-end/routes/Auth/SignUp/index.js
  back-end/routes/Auth/index.js
  back-end/routes/Chat/index.js
  back-end/routes/Comment/index.js
  back-end/routes/Search/Courses/index.js
  back-end/routes/Search/File/index.js
  back-end/routes/Search/Files/index.js
  back-end/routes/Search/Files/index.test.js
  back-end/routes/Search/Unis/index.js
  back-end/routes/Search/index.js
  back-end/routes/index.js
  back-end/server.js
Labels: task, backend

#168 Julie frontend chat
  front-end/src/App.js
  front-end/src/components/Mobile/ChatBubble/index.js
  front-end/src/components/Mobile/ChatBubble/styles.scss
  front-end/src/components/Mobile/MessageInput/index.js
  front-end/src/components/Mobile/MessageInput/styles.scss
  front-end/src/components/Mobile/UserAvatar/index.js
  front-end/src/pages/Account/Account/index.js
  front-end/src/pages/Account/Account/styles.scss
  front-end/src/pages/Chat/ChatList/index.js
  front-end/src/pages/Chat/ChatMessages/index.js
Labels: task, frontend

#169 Had287 back end gridfs, multer
  back-end/Controllers/FileController/index.js
  back-end/Controllers/UserController/index.js
  back-end/Middleware/index.js
  back-end/Services/CommentService/index.test.js
  back-end/Services/Database/index.js
  back-end/Services/FileService/index.js
  back-end/package.json
  back-end/routes/Search/File/index.js
  back-end/server.js
  back-end/yarn.lock
Labels: task, backend

#172 Had287 file comments user auth
  back-end/Controllers/ChatController/index.js
  back-end/Controllers/CommentController/index.js
  back-end/Controllers/CourseController/index.js
  back-end/Controllers/FileController/index.js
  back-end/Controllers/UniController/index.js
  back-end/Controllers/UserController/index.js
  back-end/Models/Chat/Chat.js
  back-end/Models/Chat/Message.js
  back-end/Models/Chat/index.js
  back-end/Models/index.js
  back-end/Services/ChatService/index.js
  back-end/Services/CommentService/index.js
  back-end/Services/CourseService/index.js
  back-end/Services/FileService/index.js
  back-end/Services/UniService/index.js
  back-end/Services/UserService/index.js
  back-end/routes/Chat/index.js
  back-end/routes/Comment/index.js
  back-end/routes/Search/File/index.js
  back-end/server.js
Labels: task, backend

#176 Had287 real time chat socket io
  back-end/Controllers/ChatController/index.js
  back-end/Models/Chat/Chat.js
  back-end/Models/Chat/Message.js
  back-end/Services/ChatService/index.js
  back-end/Services/WebSocketService/index.js
  back-end/package.json
  back-end/routes/Chat/index.js
  back-end/server.js
  back-end/webSocketServer.js
  back-end/yarn.lock
Labels: task, backend

#178 Kaan karaks front
  front-end/src/tests/BottomNav.test.js
  front-end/src/tests/Breadcrumbs.test.js
  front-end/src/tests/Navigations.test.js
  front-end/src/tests/PageTitle.test.js
  front-end/src/tests/PagesAddFile.test.js
  front-end/src/tests/PagesFilePreview.test.js
  front-end/src/tests/PagesLogin.test.js
  front-end/src/tests/PagesResetPass.test.js
  front-end/src/tests/PagesSignUp.test.js
Labels: frontend
